//
// Created by Sachrag Zaanzab Borzood on 2020-01-28.
//

#ifndef BICHLEGCHPLAYER_MACRO_H
#define BICHLEGCHPLAYER_MACRO_H

#define THREAD_MAIN 1
#define THREAD_CHILD 2

#define FFMPEG_CAN_NOT_OPEN_URL -1
#define FFMPEG_CAN_NOT_FIND_STREAMS -2
#define FFMPEG_FIND_DECODER_FAIL -3
#define FFMPEG_ALLOC_CODEC_CONTEXT_FAIL -4
#define FFMPEG_CODEC_CONTEXT_PARAMETERS_FAIL -5
#define FFMPEG_OPEN_DECODER_FAIL -6
#define FFMPEG_NOMEDIA -7

#define FFMPEG_READ_PACKETS_FAIL (ERROR_CODE_FFMPEG_PLAY - 8)

#endif //BICHLEGCHPLAYER_MACRO_H
